export const attributes = {
  html: [],
  head: [],
  body: ["background", "bgcolor"],
  base: ["href", "target"],
  link: [
    "as",
    "crossorigin",
    "href",
    "hreflang",
    "integrity",
    "media",
    "referrerpolicy",
    "rel",
    "sizes",
    "type",
  ],
  meta: ["charset", "content", "http-equiv", "name"],
  script: [
    "async",
    "crossorigin",
    "defer",
    "integrity",
    "language",
    "referrerpolicy",
    "src",
    "type",
  ],
  style: ["media", "scopedNon-standard", "type"],
  title: [],
  a: [
    "download",
    "href",
    "hreflang",
    "media",
    "ping",
    "referrerpolicy",
    "rel",
    "shape",
    "target",
  ],
  abbr: [],
  address: [],
  area: [
    "alt",
    "coords",
    "download",
    "href",
    "media",
    "ping",
    "referrerpolicy",
    "rel",
    "shape",
    "target",
  ],
  article: [],
  aside: [],
  audio: [
    "autoplay",
    "controls",
    "crossorigin",
    "loop",
    "muted",
    "preload",
    "src",
  ],
  b: [],
  bdi: [],
  bdo: [],
  blockquote: ["cite"],
  br: [],
  button: [
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "name",
    "type",
    "value",
  ],
  canvas: ["height", "width"],
  caption: ["align"],
  cite: [],
  code: [],
  col: ["align", "bgcolor", "span"],
  colgroup: ["align", "bgcolor", "span"],
  data: ["value"],
  datalist: [],
  dd: [],
  del: ["cite", "datetime"],
  details: ["open"],
  dfn: [],
  dialog: ["open"],
  div: [],
  dl: [],
  dt: [],
  em: [],
  embed: ["height", "src", "type", "width"],
  fieldset: ["disabled", "form", "name"],
  figcaption: [],
  figure: [],
  footer: [],
  form: [
    "accept",
    "accept-charset",
    "action",
    "autocomplete",
    "enctype",
    "method",
    "name",
    "novalidate",
    "target",
  ],
  h1: [],
  header: [],
  hgroup: [],
  hr: ["align", "color"],
  i: [],
  iframe: [
    "align",
    "allow",
    "csp",
    "height",
    "loading",
    "name",
    "referrerpolicy",
    "sandbox",
    "src",
    "srcdoc",
    "width",
  ],
  img: [
    "align",
    "alt",
    "border",
    "crossorigin",
    "decoding",
    "elementtiming",
    "height",
    "intrinsicsize",
    "ismap",
    "loading",
    "referrerpolicy",
    "sizes",
    "src",
    "srcset",
    "usemap",
    "width",
  ],
  input: [
    "accept",
    "alt",
    "autocomplete",
    "capture",
    "checked",
    "dirname",
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "height",
    "list",
    "max",
    "maxlength",
    "minlength",
    "min",
    "multiple",
    "name",
    "pattern",
    "placeholder",
    "readonly",
    "required",
    "size",
    "src",
    "step",
    "type",
    "usemap",
    "value",
    "width",
  ],
  ins: ["cite", "datetime"],
  kbd: [],
  label: ["for", "form"],
  legend: [],
  li: ["value"],
  main: [],
  map: ["name"],
  mark: [],
  menu: ["type"],
  meter: ["form", "high", "low", "max", "min", "optimum", "value"],
  nav: [],
  noscript: [],
  object: [
    "border",
    "data",
    "form",
    "height",
    "name",
    "type",
    "usemap",
    "width",
  ],
  ol: ["reversed", "start", "type"],
  optgroup: ["disabled", "label"],
  option: ["disabled", "label", "selected", "value"],
  output: ["for", "form", "name"],
  p: ["elementtiming"],
  picture: [],
  pre: [],
  progress: ["form", "max", "value"],
  q: ["cite"],
  rp: [],
  rt: [],
  ruby: [],
  s: [],
  samp: [],
  search: [],
  section: [],
  select: [
    "autocomplete",
    "disabled",
    "form",
    "multiple",
    "name",
    "required",
    "size",
  ],
  slot: [],
  small: [],
  source: ["media", "sizes", "src", "srcset", "type"],
  span: [],
  strong: [],
  sub: [],
  summary: [],
  sup: [],
  table: ["align", "background", "bgcolor", "border", "summary"],
  tbody: ["align", "bgcolor"],
  td: ["align", "background", "bgcolor", "colspan", "headers", "rowspan"],
  template: [],
  textarea: [
    "autocomplete",
    "cols",
    "dirname",
    "disabled",
    "enterkeyhint",
    "form",
    "inputmode",
    "maxlength",
    "minlength",
    "name",
    "placeholder",
    "readonly",
    "required",
    "rows",
    "wrap",
  ],
  tfoot: ["align", "bgcolor"],
  th: [
    "align",
    "background",
    "bgcolor",
    "colspan",
    "headers",
    "rowspan",
    "scope",
  ],
  thead: ["align"],
  time: ["datetime"],
  tr: ["align", "bgcolor"],
  track: ["default", "kind", "label", "src", "srclang"],
  u: [],
  ul: [],
  var: [],
  video: [
    "autoplay",
    "controls",
    "crossorigin",
    "height",
    "loop",
    "muted",
    "playsinline",
    "poster",
    "preload",
    "src",
    "width",
  ],
  wbr: [],
};
