export const non_global_attributes = {
  accept: ["form", "input"],
  "accept-charset": ["form"],
  action: ["form"],
  align: [
    "caption",
    "col",
    "colgroup",
    "hr",
    "iframe",
    "img",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
  ],
  allow: ["iframe"],
  alt: ["area", "img", "input"],
  as: ["link"],
  async: ["script"],
  autocomplete: ["form", "input", "select", "textarea"],
  autoplay: ["audio", "video"],
  background: ["body", "table", "td", "th"],
  bgcolor: [
    "body",
    "col",
    "colgroup",
    "marquee",
    "table",
    "tbody",
    "tfoot",
    "td",
    "th",
    "tr",
  ],
  border: ["img", "object", "table"],
  capture: ["input"],
  charset: ["meta"],
  checked: ["input"],
  cite: ["blockquote", "del", "ins", "q"],
  color: ["font", "hr"],
  cols: ["textarea"],
  colspan: ["td", "th"],
  content: ["meta"],
  controls: ["audio", "video"],
  coords: ["area"],
  crossorigin: ["audio", "img", "link", "script", "video"],
  csp: ["iframe"],
  data: ["object"],
  datetime: ["del", "ins", "time"],
  decoding: ["img"],
  default: ["track"],
  defer: ["script"],
  dirname: ["input", "textarea"],
  disabled: [
    "button",
    "fieldset",
    "input",
    "optgroup",
    "option",
    "select",
    "textarea",
  ],
  download: ["a", "area"],
  enctype: ["form"],
  enterkeyhint: ["textarea", "contenteditable"],
  elementtiming: ["img", "image", "p"],
  for: ["label", "output"],
  form: [
    "button",
    "fieldset",
    "input",
    "label",
    "meter",
    "object",
    "output",
    "progress",
    "select",
    "textarea",
  ],
  formaction: ["input", "button"],
  formenctype: ["button", "input"],
  formmethod: ["button", "input"],
  formnovalidate: ["button", "input"],
  formtarget: ["button", "input"],
  headers: ["td", "th"],
  height: ["canvas", "embed", "iframe", "img", "input", "object", "video"],
  high: ["meter"],
  href: ["a", "area", "base", "link"],
  hreflang: ["a", "link"],
  "http-equiv": ["meta"],
  integrity: ["link", "script"],
  intrinsicsize: ["img"],
  inputmode: ["textarea", "contenteditable"],
  ismap: ["img"],
  kind: ["track"],
  label: ["optgroup", "option", "track"],
  language: ["script"],
  loading: ["img", "iframe"],
  list: ["input"],
  loop: ["audio", "marquee", "video"],
  low: ["meter"],
  max: ["input", "meter", "progress"],
  maxlength: ["input", "textarea"],
  minlength: ["input", "textarea"],
  media: ["a", "area", "link", "source", "style"],
  method: ["form"],
  min: ["input", "meter"],
  multiple: ["input", "select"],
  muted: ["audio", "video"],
  name: [
    "button",
    "form",
    "fieldset",
    "iframe",
    "input",
    "object",
    "output",
    "select",
    "textarea",
    "map",
    "meta",
    "param",
  ],
  novalidate: ["form"],
  open: ["details", "dialog"],
  optimum: ["meter"],
  pattern: ["input"],
  ping: ["a", "area"],
  placeholder: ["input", "textarea"],
  playsinline: ["video"],
  poster: ["video"],
  preload: ["audio", "video"],
  readonly: ["input", "textarea"],
  referrerpolicy: ["a", "area", "iframe", "img", "link", "script"],
  rel: ["a", "area", "link"],
  required: ["input", "select", "textarea"],
  reversed: ["ol"],
  rows: ["textarea"],
  rowspan: ["td", "th"],
  sandbox: ["iframe"],
  scope: ["th"],
  "scopedNon-standard": ["style"],
  selected: ["option"],
  shape: ["a", "area"],
  size: ["input", "select"],
  sizes: ["link", "img", "source"],
  span: ["col", "colgroup"],
  src: [
    "audio",
    "embed",
    "iframe",
    "img",
    "input",
    "script",
    "source",
    "track",
    "video",
  ],
  srcdoc: ["iframe"],
  srclang: ["track"],
  srcset: ["img", "source"],
  start: ["ol"],
  step: ["input"],
  summary: ["table"],
  target: ["a", "area", "base", "form"],
  type: [
    "button",
    "input",
    "embed",
    "object",
    "ol",
    "script",
    "source",
    "style",
    "menu",
    "link",
  ],
  usemap: ["img", "input", "object"],
  value: [
    "button",
    "data",
    "input",
    "li",
    "meter",
    "option",
    "progress",
    "param",
  ],
  width: ["canvas", "embed", "iframe", "img", "input", "object", "video"],
  wrap: ["textarea"],
};
